graph:	graph.c polish_math.c polish_pars.c stack.c
	gcc -Wall -Werror -Wextra -o ../build/graph graph.c polish_math.c polish_pars.c stack.c

all: graph

clean: 
	rm -rf ./*.o ../build/graph

rebuild: clean all
